included:
  - Sources
  - Tests

excluded:
  - .build
  - Package.swift

disabled_rules:
  - trailing_comma
  - identifier_name
  - type_name
  - nesting
  - function_body_length
  - file_length
  - type_body_length
  - cyclomatic_complexity
  - large_tuple

opt_in_rules:
  - empty_count
  - empty_string
  - closure_spacing
  - contains_over_first_not_nil
  - discouraged_optional_boolean
  - fatal_error_message
  - first_where
  - force_unwrapping
  - implicitly_unwrapped_optional
  - last_where
  - literal_expression_end_indentation
  - modifier_order
  - operator_usage_whitespace
  - overridden_super_call
  - prefer_zero_over_explicit_init
  - private_action
  - private_outlet
  - prohibited_super_call
  - redundant_nil_coalescing
  - sorted_first_last
  - toggle_bool
  - unavailable_function
  - unneeded_parentheses_in_closure_argument
  - vertical_parameter_alignment_on_call
  - yoda_condition

line_length:
  warning: 150
  error: 200
  ignores_urls: true
  ignores_comments: true
  ignores_interpolated_strings: true

function_parameter_count:
  warning: 8
  error: 10

reporter: xcode
